
language: android

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra

script: "./gradlew build"

env:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
before_install:
     - chmod +x gradlew

sudo: false